[qt]
GUIEffects=none
KDE\contrast=7
KWinPalette\activeBackground=#30aee8
KWinPalette\activeBlend=#d6d2d0
KWinPalette\activeForeground=#ffffff
KWinPalette\activeTitleBtnBg=#d6d2d0
KWinPalette\frame=#d6d2d0
KWinPalette\inactiveBackground=#e0dfde
KWinPalette\inactiveBlend=#d9d1ce
KWinPalette\inactiveForeground=#4b4743
KWinPalette\inactiveFrame=#d9d1ce
KWinPalette\inactiveTitleBtnBg=#d9d1ce
Palette\active=#221f1e, #dfdcd9, #fcfcfc, #e1dedd, #6a6663, #b3aba7, #1f1c1b, #ffffff, #221f1e, #ffffff, #d6d2d0, #3e3b3a, #43ace8, #ffffff, #0057ae, #644a9b, #f8f7f6, #000000, #181513, #e7fdff, #898887, #43ace8
Palette\disabled=#908c8b, #d6d2ce, #f2f1f0, #d9d5d3, #65615f, #aba4a0, #a9a7a7, #ffffff, #969390, #f3f3f3, #cdc8c5, #3d3a39, #cdc8c5, #908c8b, #97bcdf, #c1b6d7, #eeebe9, #000000, #181513, #e7fdff, #cccbcb, #cdc8c5
Palette\inactive=#2f2d2b, #e1dcd6, #fdfcfc, #e3dedb, #6d6560, #b8aaa2, #313030, #ffffff, #302e2c, #ffffff, #d9d1ce, #403b38, #77cdff, #192e3a, #196595, #7c3ccc, #f9f7f5, #000000, #181513, #e7fdff, #8e8d8c, #77cdff
font="Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
